services:
  web:
    build: ./novelot-frontend/
    ports:
      - 5173:5173
    env_file:
      - ./novelot-frontend/.env
    depends_on:
      - app
  app:
    build: ./novelot-backend/
    ports:
      - "1714:1714"
    env_file: 
      - ./novelot-backend/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d  # ← runs on first startup
      - ./myfile.json:/data/import/myfile.json    # ← your json file
      - ./novelot-backend/src/assets/novelList.json:/data/import/novelList.json
      - ./novelot-backend/src/assets/userList.json:/data/import/userList.json

volumes:
  mongo_data:

